import Vue from "vue";

import {
    Dialog,
    Row,
    Col,
    Picker,
    Field,
    Cell,
    CellGroup,
    Button,
    Toast,
    NavBar,
    Tabbar,
    TabbarItem,
    List,
    Panel,
    NoticeBar,
    Tag,
    Popup,
    Notify,
    Icon,
    DropdownMenu,
    DropdownItem,
    Tab,
    Tabs,
    Grid,
    GridItem,
    Divider,
    Uploader,
    PullRefresh,
    SwipeCell,
    RadioGroup,
    Radio,
    Switch,
    ActionSheet,
    Overlay,
    Loading,
    IndexBar,
    IndexAnchor,
    Search,
    Stepper,
    Empty,
    Area,
    Form,
    Sticky,
    NumberKeyboard,
    TreeSelect,
    Checkbox,
    CheckboxGroup,
    DatetimePicker,
    Swipe,
    SwipeItem,
    Image as VanImage,
    Card,
    ImagePreview,
    GoodsAction,
    GoodsActionIcon,
    GoodsActionButton,
    Sidebar,
    SidebarItem,
     Sku 
   // Badge,
} from "vant";

Vue.use(Card);
Vue.use(VanImage);
Vue.use(TreeSelect);
Vue.use(DatetimePicker);
Vue.use(NumberKeyboard);
Vue.use(Sticky);
Vue.use(Form);
Vue.use(Area);
Vue.use(Empty);
Vue.use(Stepper);
Vue.use(Search);
Vue.use(IndexBar);
Vue.use(IndexAnchor);
Vue.use(Loading);
Vue.use(Overlay);
Vue.use(ActionSheet);
Vue.use(Switch);
Vue.use(Radio);
Vue.use(RadioGroup);
Vue.use(SwipeCell);
Vue.use(Divider);
Vue.use(Row).use(Col);
Vue.use(Field);
Vue.use(Cell).use(CellGroup);
Vue.use(Button);
Vue.use(Toast);
Vue.use(NavBar);
Vue.use(Tabbar).use(TabbarItem);
Vue.use(DropdownMenu).use(DropdownItem);
Vue.use(Panel);
Vue.use(List);
Vue.use(NoticeBar);
Vue.use(Tag);
Vue.use(Popup);
Vue.use(Picker);
Vue.use(Dialog);
Vue.use(Notify);
Vue.use(Icon);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(Uploader);
Vue.use(PullRefresh);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(ImagePreview);
Vue.use(GoodsAction);
Vue.use(GoodsActionButton);
Vue.use(GoodsActionIcon);
Vue.use(Sku);
Vue.use(Sidebar);
Vue.use(SidebarItem);
//Vue.use(Badge);